services:
  gym-evolution:
    build: .
    ports:
      - '3001:3001'
    environment:
      DATABASE_URL: postgresql://lucaslevingston:123@db-postgre-gym-evolution:5432/gym-evolution?schema=public
    depends_on:
      - db-postgre-gym-evolution
    command: npm run dev

  db-postgre-gym-evolution:
    image: postgres
    restart: always
    volumes:
      - ./gym-evolution-api:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: lucaslevingston
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: gym-evolution

volumes:
  gym-evolution-api:
